version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on: 
      - backend
    ports:
      - 80:80
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 9000:9000
    